### ISSUE TITLE
Mutations support?

### ISSUE THREAD

**Issue by alexander-mart** [amoutonbrady/graphql-client#2]

**Comment by amoutonbrady** [comment]
Hi,

Thanks for the interest and sorry for the delayed response. I'm still new to OSS and it seems like some issues get filtered out of my notification somehow...

Anyway, the goal of the library is to be extremely minimal, in fact I could almost paste its compiled source code here.

GraphQL is just a "normalized" POST request with a `query` param and a `variable` param. No matter if it's a Query or a Mutation.

Therefore, you should be able to use the `request` method with Mutation.

Here's an example : https://codesandbox.io/s/mutation-b3seb?file=/src/index.js
